import pytest
import docker
import time
import re
import uuid
from typing import List

from docker.types import Healthcheck
from nginx.NginxConf import HttpBlock, NginxConfig, ServerBlock
from tests.helpers.docker_utils import start_backend, start_nginx_proxy_container, stop_backend
from tests.helpers import (
    get_nginx_config_from_container,
    expect_server_down_integration,
    expect_server_not_present_integration,
    expect_server_up_integration,
)


pytestmark = pytest.mark.swarm_mode("enable")


# Regex to match the dynamically assigned IP:PORT for proxy_pass
# Example: http://172.18.0.2:80
pattern = re.compile(r"^http://\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:80")
START_GRACE_SECONDS = 2


def test_certapi_unresolvable_hostname_does_not_crash_nginx_startup(
    docker_client,
    test_network,
    swarm_mode,
):
    image_name = "mesudip/nginx-proxy:test"
    container_name = f"nginx-proxy-certapi-unresolved-{swarm_mode}-{uuid.uuid4().hex[:8]}"
    container = None

    docker_client.images.build(path=".", tag=image_name, rm=True)

    try:
        container = docker_client.containers.run(
            image_name,
            detach=True,
            volumes={
                "/var/run/docker.sock": {"bind": "/var/run/docker.sock", "mode": "ro"},
                "nginx-test-dhparam": {"bind": "/etc/nginx/dhparam", "mode": "rw"},
                "nginx-test-ssl": {"bind": "/etc/ssl", "mode": "rw"},
            },
            network=test_network.name,
            name=container_name,
            environment={
                "CERTAPI_URL": "https://nonresolving-domain",
                "LETSENCRYPT_API": "https://acme-staging-v02.api.letsencrypt.org/directory",
                "VHOSTS_TEMPLATE_DIR": "/app/vhosts_template",
                "CHALLENGE_DIR": "/etc/nginx/acme-challenges",
                "DOCKER_SWARM": swarm_mode,
                "BACKEND_START_GRACE_SECONDS": "2",
            },
            restart_policy={"Name": "no"},
        )

        time.sleep(5)
        container.reload()
        logs = container.logs(stdout=True, stderr=True).decode("utf-8", errors="replace")

        assert container.status == "running", logs
        assert "host not found in upstream" not in logs
    finally:
        if container:
            print("=========================== Container Logs Start ===========================")
            print(container.logs(stdout=True, stderr=True).decode("utf-8", errors="replace"))
            print("=========================== Container Logs End ===========================")
            container.remove(force=True)


def _http_healthcheck() -> Healthcheck:
    return Healthcheck(
        test="node -e \"require('http').get('http://127.0.0.1:8080', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))\"",
        interval=1_000_000_000,
        timeout=1_000_000_000,
        retries=2,
        start_period=0,
    )


def _marker_healthcheck() -> Healthcheck:
    return Healthcheck(
        test="test -f /tmp/nginx-proxy-health-ready && node -e \"require('http').get('http://127.0.0.1:8080', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))\"",
        interval=1_000_000_000,
        timeout=1_000_000_000,
        retries=1,
        start_period=0,
    )


def test_webserver_initialization_integration(nginx_proxy_container: docker.models.containers.Container):
    """
    Test the initial Nginx configuration generated by the proxy container.
    Should contain a default 503 server.
    """
    container, _, _ = nginx_proxy_container
    config_str = get_nginx_config_from_container(container)
    config = NginxConfig()
    full_config_str = f"http {{\n{config_str}\n}}"  # NginxConfig expects full http block
    config.load(full_config_str)

    # Find the default server
    default_server = None
    for server in config.http.servers:
        if "default_server" in server.listen:
            default_server = server
            break

    assert default_server is not None, "Default server block not found."
    assert default_server.server_names == ["_"]
    assert default_server.error_page == "503 /503_default.html"

    # Check locations within the default server
    assert len(default_server.locations) >= 3  # At least 3 locations: acme, 503_default, /

    acme_loc = next((loc for loc in default_server.locations if loc.path == "/.well-known/acme-challenge/"), None)
    assert acme_loc is not None
    assert acme_loc.alias == "/etc/nginx/acme-challenges/"  # This path is inside the container
    assert acme_loc.try_files == "$uri =404"

    error_loc = next((loc for loc in default_server.locations if loc.path == "= /503_default.html"), None)
    assert error_loc is not None
    assert error_loc.root == "/app/vhosts_template/errors"  # This path is inside the container
    assert error_loc.internal is not None

    root_loc = next((loc for loc in default_server.locations if loc.path == "/"), None)
    assert root_loc is not None
    assert root_loc.return_code == "503"


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_webserver_add_container_integration(
    nginx_proxy_container,
    docker_client,
    test_network,
    backend_type,
):
    """
    Test that adding a container/service with VIRTUAL_HOST creates a corresponding Nginx server block.
    """
    virtual_host = f"{backend_type}.add-{uuid.uuid4().hex[:6]}.example.com"
    env = {"VIRTUAL_HOST": virtual_host}
    backend = None
    try:
        backend = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)

        server = expect_server_up_integration(nginx_proxy_container[0], virtual_host, timeout=15)

    finally:
        if backend:
            stop_backend(backend)


def test_new_basic_auth_backend_is_accepted_after_candidate_validation(
    nginx_proxy_container,
    docker_client,
    test_network,
):
    virtual_host = f"basic-auth-{uuid.uuid4().hex[:6]}.example.com"
    backend = None
    try:
        backend = start_backend(
            docker_client,
            test_network,
            {
                "VIRTUAL_HOST": virtual_host,
                "PROXY_BASIC_AUTH": "testuser:testpassword",
            },
            sleep=False,
        )

        expect_server_up_integration(nginx_proxy_container[0], virtual_host, timeout=20)
        result, output = nginx_proxy_container[0].exec_run(f"test -s /etc/nginx/basic_auth/{virtual_host}/_")
        assert result == 0, output.decode("utf-8")
    finally:
        if backend:
            stop_backend(backend)


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_invalid_backend_config_is_ignored_and_does_not_poison_future_updates_integration(
    nginx_proxy_container,
    docker_client,
    test_network,
    backend_type,
):
    good_host_1 = f"{backend_type}.valid-before-{uuid.uuid4().hex[:6]}.example.com"
    bad_host = f"{backend_type}.invalid-{uuid.uuid4().hex[:6]}.example.com"
    good_host_2 = f"{backend_type}.valid-after-{uuid.uuid4().hex[:6]}.example.com"

    good_backend_1 = None
    bad_backend = None
    good_backend_2 = None
    try:
        good_backend_1 = start_backend(
            docker_client,
            test_network,
            {"VIRTUAL_HOST": good_host_1},
            backend_type=backend_type,
            sleep=False,
        )
        expect_server_up_integration(nginx_proxy_container[0], good_host_1, timeout=20)

        bad_backend = start_backend(
            docker_client,
            test_network,
            {"VIRTUAL_HOST": f"{bad_host}; invalid_nginx_directive value"},
            backend_type=backend_type,
            sleep=False,
        )
        expect_server_not_present_integration(nginx_proxy_container[0], bad_host, timeout=15)
        expect_server_up_integration(nginx_proxy_container[0], good_host_1, timeout=5)

        good_backend_2 = start_backend(
            docker_client,
            test_network,
            {"VIRTUAL_HOST": good_host_2},
            backend_type=backend_type,
            sleep=False,
        )
        expect_server_up_integration(nginx_proxy_container[0], good_host_2, timeout=20)
        expect_server_up_integration(nginx_proxy_container[0], good_host_1, timeout=5)
        expect_server_not_present_integration(nginx_proxy_container[0], bad_host, timeout=5)

        result, output = nginx_proxy_container[0].exec_run("nginx -t")
        assert result == 0, output.decode("utf-8")
    finally:
        for backend in (good_backend_1, bad_backend, good_backend_2):
            if backend:
                stop_backend(backend)


def test_startup_ignores_existing_backend_with_nginx_rejected_virtual_host_config_integration(
    docker_client,
    test_network,
    docker_host_ip,
    swarm_mode,
):
    good_host = f"startup-valid-{uuid.uuid4().hex[:6]}.example.com"
    bad_host = f"startup-invalid-{uuid.uuid4().hex[:6]}.example.com"

    good_backend = None
    bad_backend = None
    proxy_container = None
    try:
        good_backend = start_backend(
            docker_client,
            test_network,
            {"VIRTUAL_HOST": good_host, "VIRTUAL_PORT": "8080"},
            backend_type="container",
            sleep=False,
        )
        bad_backend = start_backend(
            docker_client,
            test_network,
            {
                "VIRTUAL_HOST": f"https://{bad_host};unknown_key -1;",
                "VIRTUAL_PORT": "8080",
            },
            backend_type="container",
            sleep=False,
        )

        proxy_container, _, _ = start_nginx_proxy_container(
            docker_client,
            test_network,
            docker_host_ip,
            swarm_mode,
            f"nginx-proxy-startup-invalid-{swarm_mode}-{uuid.uuid4().hex[:8]}",
            backend_start_grace_seconds="2",
        )

        expect_server_up_integration(proxy_container, good_host, timeout=20)
        expect_server_not_present_integration(proxy_container, bad_host, timeout=10)

        result, output = proxy_container.exec_run("nginx -t")
        assert result == 0, output.decode("utf-8")

        logs = proxy_container.logs().decode("utf-8")
        assert "unknown_key" in logs
    finally:
        if proxy_container:
            print("=========================== Container Logs Start ===========================")
            print(proxy_container.logs().decode("utf-8"))
            print("=========================== Container Logs End ===========================")
            proxy_container.remove(force=True)
        for backend in (good_backend, bad_backend):
            if backend:
                stop_backend(backend)


def test_container_start_grace_delays_config_update(
    docker_client,
    test_network,
    docker_host_ip,
    swarm_mode,
):
    grace_seconds = 10
    virtual_host = f"container.grace-{uuid.uuid4().hex[:6]}.example.com"
    proxy_container = None
    backend = None
    try:
        proxy_container, _, _ = start_nginx_proxy_container(
            docker_client,
            test_network,
            docker_host_ip,
            swarm_mode,
            f"nginx-proxy-grace-{swarm_mode}-{uuid.uuid4().hex[:8]}",
            backend_start_grace_seconds=str(grace_seconds),
        )

        backend = start_backend(
            docker_client,
            test_network,
            {"VIRTUAL_HOST": virtual_host},
            backend_type="container",
            sleep=False,
        )
        backend_started_at = time.monotonic()

        time.sleep(max(0, 5 - (time.monotonic() - backend_started_at)))
        expect_server_not_present_integration(proxy_container, virtual_host, timeout=1)

        time.sleep(max(0, 12 - (time.monotonic() - backend_started_at)))
        expect_server_up_integration(proxy_container, virtual_host, timeout=3)
    finally:
        if proxy_container:
            print("=========================== Container Logs Start ===========================")
            print(proxy_container.logs().decode("utf-8"))
            print("=========================== Container Logs End ===========================")
            proxy_container.remove(force=True)
        if backend:
            stop_backend(backend)


def test_healthchecked_container_waits_until_healthy_integration(
    nginx_proxy_container,
    docker_client,
    test_network,
):
    virtual_host = f"container.health-{uuid.uuid4().hex[:6]}.example.com"
    backend = None
    try:
        backend = start_backend(
            docker_client,
            test_network,
            {"VIRTUAL_HOST": virtual_host, "VIRTUAL_PORT": "8080"},
            backend_type="container",
            sleep=False,
            healthcheck=_marker_healthcheck(),
        )

        time.sleep(START_GRACE_SECONDS + 1)
        expect_server_not_present_integration(nginx_proxy_container[0], virtual_host, timeout=1)

        backend.exec_run("touch /tmp/nginx-proxy-health-ready")

        expect_server_up_integration(nginx_proxy_container[0], virtual_host, timeout=20)
    finally:
        if backend:
            stop_backend(backend)


def test_healthchecked_service_is_discovered_integration(
    nginx_proxy_container,
    docker_client,
    test_network,
):
    virtual_host = f"service.health-{uuid.uuid4().hex[:6]}.example.com"
    backend = None
    try:
        backend = start_backend(
            docker_client,
            test_network,
            {"VIRTUAL_HOST": virtual_host, "VIRTUAL_PORT": "8080"},
            backend_type="service",
            sleep=False,
            healthcheck=_http_healthcheck(),
        )

        expect_server_up_integration(nginx_proxy_container[0], virtual_host, timeout=20)
    finally:
        if backend:
            stop_backend(backend)


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_webserver_remove_container_integration(
    nginx_proxy_container,
    docker_client,
    test_network,
    backend_type,
):
    """
    Test that removing a container/service with VIRTUAL_HOST removes its Nginx server block
    or converts it to a 503 error page.
    """
    virtual_host = f"{backend_type}.remove-{uuid.uuid4().hex[:6]}.example.com"
    env = {"VIRTUAL_HOST": virtual_host}

    backend = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)
    expect_server_up_integration(nginx_proxy_container[0], virtual_host, timeout=15)

    stop_backend(backend)

    expect_server_down_integration(nginx_proxy_container[0], virtual_host, timeout=15)


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_webserver_add_network_integration(
    nginx_proxy_container: docker.models.containers.Container,
    docker_client: docker.DockerClient,
    test_network: docker.models.networks.Network,
    backend_type: str,
):
    """
    Test that connecting a container/service to the proxy's network adds its Nginx server block.
    """
    if backend_type == "service":
        pytest.skip("Dynamic network attachment for services requires mock update logic")

    virtual_host = backend_type + "." + "addnet.example.com"
    env = {"VIRTUAL_HOST": virtual_host}

    # Create container on a different network first
    other_network_name = "other-test-network"
    other_network = docker_client.networks.create(other_network_name, driver="bridge")
    backend = None
    try:
        backend = start_backend(docker_client, other_network, env, backend_type=backend_type, sleep=False)

        expect_server_not_present_integration(nginx_proxy_container[0], virtual_host, timeout=15)

        # Connect the container to the test_network (frontend network for the proxy)
        test_network.connect(backend)

        expect_server_up_integration(nginx_proxy_container[0], virtual_host, timeout=15)
    finally:
        if backend:
            backend.remove(force=True)
        if other_network:
            other_network.remove()


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_webserver_remove_network_integration(
    nginx_proxy_container: docker.models.containers.Container,
    docker_client: docker.DockerClient,
    test_network: docker.models.networks.Network,
    backend_type: str,
):
    """
    Test that disconnecting a container from the proxy's network removes its Nginx server block.
    Same limitation as add_network for services.
    """
    if backend_type == "service":
        pytest.skip("Dynamic network detachment for services requires mock update logic")

    virtual_host = backend_type + "." + "removenet.example.com"
    env = {"VIRTUAL_HOST": virtual_host}

    backend = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)
    expect_server_up_integration(nginx_proxy_container[0], virtual_host, timeout=15)

    # Disconnect the container from the test_network
    test_network.disconnect(backend)

    expect_server_down_integration(nginx_proxy_container[0], virtual_host, timeout=15)

    stop_backend(backend)  # Clean up


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_webserver_recreate_same_name_container_with_different_host_integration(
    nginx_proxy_container: docker.models.containers.Container,
    docker_client: docker.DockerClient,
    test_network: docker.models.networks.Network,
    backend_type: str,
):
    """
    Test that recreating a container/service with the same name but a different VIRTUAL_HOST
    correctly updates the Nginx configuration.
    """
    old_virtual_host = backend_type + "." + "old.example.com"
    new_virtual_host = backend_type + "." + "new.example.com"

    # Create with old env
    backend_old = start_backend(
        docker_client, test_network, {"VIRTUAL_HOST": old_virtual_host}, backend_type=backend_type, sleep=False
    )
    expect_server_up_integration(nginx_proxy_container[0], old_virtual_host, timeout=15)

    # Remove the old backend
    stop_backend(backend_old)

    expect_server_down_integration(nginx_proxy_container[0], old_virtual_host, timeout=15)

    backend_new = start_backend(
        docker_client, test_network, {"VIRTUAL_HOST": new_virtual_host}, backend_type=backend_type, sleep=False
    )
    try:
        expect_server_up_integration(nginx_proxy_container[0], new_virtual_host, timeout=15)
        expect_server_down_integration(nginx_proxy_container[0], old_virtual_host, timeout=15)
    finally:
        if backend_new:
            stop_backend(backend_new)


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_webserver_add_container_with_ssl_integration(
    nginx_proxy_container: docker.models.containers.Container,
    docker_client: docker.DockerClient,
    test_network: docker.models.networks.Network,
    backend_type: str,
):
    """
    Test that adding a container/service with an HTTPS VIRTUAL_HOST creates both HTTP redirect
    and HTTPS server blocks with self-signed certificates.
    """
    virtual_host = backend_type + "." + "ssl-test.example.com"
    env = {"VIRTUAL_HOST": f"https://{virtual_host}", "VIRTUAL_PORT": "8080"}

    backend = start_backend(docker_client, test_network, env, backend_type=backend_type)
    try:
        time.sleep(5)  # Sleep extra for ssl cert generation
        config_str = get_nginx_config_from_container(nginx_proxy_container[0])
        config = HttpBlock.parse(config_str)

        servers_for_host: List[ServerBlock] = [s for s in config.servers if virtual_host in s.server_names]

        assert (
            len(servers_for_host) == 2
        ), f"Expected 2 server blocks for {virtual_host}, found {len(servers_for_host)}. Config:\n{config_str}"

        https_server = next((s for s in servers_for_host if "443" in s.listen), None)
        http_redirect_server = next((s for s in servers_for_host if s.listen == "80"), None)

        assert https_server is not None, "HTTPS server block not found."
        assert http_redirect_server is not None, "HTTP redirect server block not found."

        # Verify HTTPS server is correctly configured
        assert "ssl" in https_server.listen
        assert https_server._get_directive_value("ssl_certificate").endswith(f"/{virtual_host}.selfsigned.crt")
        assert https_server._get_directive_value("ssl_certificate_key").endswith(f"/{virtual_host}.selfsigned.key")
        redirect_loc = next((loc for loc in http_redirect_server.locations if loc.path == "/"), None)
        assert redirect_loc is not None
        assert redirect_loc.return_code == f"308 https://{virtual_host}$request_uri"
    finally:
        if backend:
            stop_backend(backend)


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_proxy_full_redirect_to_https_target_integration(
    nginx_proxy_container: docker.models.containers.Container,
    docker_client: docker.DockerClient,
    test_network: docker.models.networks.Network,
    backend_type: str,
):
    """
    Test that PROXY_FULL_REDIRECT resolves a bare target to the existing HTTPS vhost
    and renders a documented 301 redirect without appending :80.
    """
    suffix = uuid.uuid4().hex[:6]
    target_host = f"{backend_type}.full-redirect-target-{suffix}.example.com"
    source_host = f"{backend_type}.full-redirect-source-{suffix}.example.com"
    env = {
        "VIRTUAL_HOST": f"https://{target_host} -> :8080",
        "VIRTUAL_PORT": "8080",
        "PROXY_FULL_REDIRECT": f"{source_host} -> {target_host}",
    }

    backend = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)
    try:
        redirect_server = None
        for _ in range(25):
            config_str = get_nginx_config_from_container(nginx_proxy_container[0])
            config = HttpBlock.parse(config_str)
            redirect_server = next((s for s in config.servers if source_host in s.server_names), None)
            if redirect_server is not None:
                redirect_loc = next((loc for loc in redirect_server.locations if loc.path == "/"), None)
                if redirect_loc and redirect_loc.return_code == f"301 https://{target_host}$request_uri":
                    break
            time.sleep(1)

        config_str = get_nginx_config_from_container(nginx_proxy_container[0])
        config = HttpBlock.parse(config_str)
        target_servers = [s for s in config.servers if target_host in s.server_names]
        source_servers = [s for s in config.servers if source_host in s.server_names]

        assert any("443" in s.listen for s in target_servers), f"HTTPS target server not found. Config:\n{config_str}"
        assert len(source_servers) == 1, f"Expected one redirect source server. Config:\n{config_str}"

        redirect_loc = next((loc for loc in source_servers[0].locations if loc.path == "/"), None)
        assert redirect_loc is not None, f"Redirect location not found. Config:\n{config_str}"
        assert redirect_loc.return_code == f"301 https://{target_host}$request_uri"
    finally:
        if backend:
            stop_backend(backend)


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_webserver_add_two_containers_with_same_virtual_host_integration(
    nginx_proxy_container,
    docker_client,
    test_network,
    backend_type,
):
    """
    Test that adding two backends with the same VIRTUAL_HOST creates an upstream block
    and the server block uses it.
    """
    virtual_host = f"{backend_type}.lb1-{uuid.uuid4().hex[:6]}.example.com"
    env = {"VIRTUAL_HOST": virtual_host}

    backend1 = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)
    backend2 = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)
    try:
        # Wait until we see an upstream with 2 servers
        upstream = None
        for _ in range(25):
            config_str = get_nginx_config_from_container(nginx_proxy_container[0])
            config = HttpBlock.parse(config_str)
            upstream = next((u for u in config.upstreams if virtual_host in u.parameters), None)
            if upstream and len(upstream.get_directives("server")) == 2:
                break
            time.sleep(1)

        config_str = get_nginx_config_from_container(nginx_proxy_container[0])
        assert upstream is not None, f"Upstream block for {virtual_host} not found after timeout. Config:\n{config_str}"
        assert (
            len(upstream.get_directives("server")) == 2
        ), f"Expected 2 servers in upstream, found {len(upstream.get_directives('server'))}. Config:\n{config_str}"
    finally:
        stop_backend(backend1)
        stop_backend(backend2)


@pytest.mark.parametrize("backend_type", ["container", "service"])
def test_when_container_shuts_down__then_ip_removed_from_upstream(
    nginx_proxy_container,
    docker_client,
    test_network,
    backend_type,
):
    """
    Test that scaling down backends updates upstreams.
    """
    virtual_host = f"{backend_type}.lb2-{uuid.uuid4().hex[:6]}.example.com"
    env = {"VIRTUAL_HOST": virtual_host}

    backend1 = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)
    backend2 = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)
    backend3 = start_backend(docker_client, test_network, env, backend_type=backend_type, sleep=False)
    try:
        # Wait for 3 backends
        upstream = None
        for _ in range(30):
            config_str = get_nginx_config_from_container(nginx_proxy_container[0])
            config = HttpBlock.parse(config_str)
            upstream = next((u for u in config.upstreams if virtual_host in u.parameters), None)
            if upstream and len(upstream.get_directives("server")) == 3:
                break
            time.sleep(1)

        config_str = get_nginx_config_from_container(nginx_proxy_container[0])
        assert upstream is not None, f"Upstream block for {virtual_host} not found. Config:\n{config_str}"
        assert (
            len(upstream.get_directives("server")) == 3
        ), f"Expected 3 servers in upstream, found {len(upstream.get_directives('server'))}. Config:\n{config_str}"

        # Stop/Remove one backend
        stop_backend(backend1)
        backend1 = None

        # Wait for update
        for _ in range(20):
            config_str = get_nginx_config_from_container(nginx_proxy_container[0])
            config = HttpBlock.parse(config_str)
            upstream = next((u for u in config.upstreams if virtual_host in u.parameters), None)
            if upstream and len(upstream.get_directives("server")) == 2:
                break
            time.sleep(1)

        assert (
            len(upstream.get_directives("server")) == 2
        ), f"Expected 2 servers in upstream, found {len(upstream.get_directives('server'))}. Config:\n{config_str}"

        stop_backend(backend2)
        backend2 = None

        # Wait for update
        for _ in range(20):
            config_str = get_nginx_config_from_container(nginx_proxy_container[0])
            config = HttpBlock.parse(config_str)
            upstream = next((u for u in config.upstreams if virtual_host in u.parameters), None)
            if upstream is None or len(upstream.get_directives("server")) == 1:
                break
            time.sleep(1)

        assert (
            upstream is None or len(upstream.get_directives("server")) == 1
        ), f"Expected 0 or 1 server in upstream, found {len(upstream.get_directives('server')) if upstream else 0}. Config:\n{config_str}"

    finally:
        for b in [backend1, backend2, backend3]:
            if b:
                stop_backend(b)
        # Wait for cleanup
        expect_server_down_integration(nginx_proxy_container[0], virtual_host, timeout=15)
